Repository xmidt-org/argus, pull requests merged in 2020-08, with the labels that each got.

#17 added copyrights to missing files and changed logger context funcs
  CHANGELOG.md
  auth.go
  chrysom/doc.go
  go.sum
  model/model.go
  store/db/provide.go
  store/dynamodb/db.go
  store/dynamodb/executer.go
Labels: documentation

#20 Small fixes
  auth.go
  routes.go
  store/handler.go
Labels: enhancement

#21 Apply auth only on supported routes
  CHANGELOG.md
  main.go
  routes.go
Labels: bug

#22 Don't encode expired ownable items
  CHANGELOG.md
  store/handler.go
Labels: bug

#23 add poll counter
  CHANGELOG.md
  chrysom/client.go
  chrysom/metrics.go
  go.sum
Labels: enhancement

#26 Simplify config -> client initialization
  CHANGELOG.md
  chrysom/client.go
  chrysom/store.go
Labels: enhancement
